apiVersion: apps/v1
kind: Deployment
metadata:
  name: obs-depl
spec:
  selector:
    matchLabels:
      app: obs
  template:
    metadata:
      labels:
        app: obs
    spec:
      containers:
      - name: obs
        image:  bandi13/docker-obs
        imagePullPolicy: Always
        env:
        - name: VNC_PASSWD
          value: '123456'
        resources: {}
        ports:
        - containerPort: 5901

---
apiVersion: v1
kind: Service
metadata:
  name: obs-svc
spec:
  selector:
    app: obs
  ports:
  - name: obs
    protocol: TCP
    port: 8080
    targetPort: 5901
