apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgan-frontend-depl
spec:
  selector:
    matchLabels:
      app: sgan-frontend
  template:
    metadata:
      labels:
        app: sgan-frontend
    spec:
      containers:
      - name: sgan-frontend
        image: eloyk/frontend
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: sgan-frontend-svc
spec:
  selector:
    app: sgan-frontend
  ports:
  - name: sgan-frontend
    protocol: TCP
    port: 8080
    targetPort: 3000
