apiVersion: apps/v1
kind: Deployment
metadata:
  name: smd-raian-depl
spec:
  selector:
    matchLabels:
      app: smd-raian
  template:
    metadata:
      labels:
        app: smd-raian
    spec:
      containers:
      - name: smd-raian
        image: eloyk/smd-beta:v1.0.6
        imagePullPolicy: Always
        env:
        - name: DB_NAME
          value: DB_SMD
        - name: SERVER_HOST
          value: mongo-svc
        - name: SERVER_PORT
          value: '27017'

        - name: FEE_PERCENT
          value: '0'
        - name: DOLLAR_COIN
          value: USDT
        - name: MIN_BUY
          value: '10'
        - name: INIT_BALANCE
          value: '400'

        #BOTs
        - name: BOTS_DB
          value: DB_BOTS_RAIAN
        # DAILY TRADE BOT
        - name: DT_CRYPTO
          value: DOT
        - name: DT_DOLLAR
          value: USDT
        - name: DT_PERCENT
          value: '3'
        - name: DT_AMOUNT
          value: '50'
        - name: API_KEY
          value: 'nOOXqrE8N2LdP37EDW0y4lzfNg6SqxNW8JjWXHyH9lkqHKKB1DiOq0CvX5pW0Sy9'
        - name: SECRET_KEY
          value: '6OTcgIlypNACle5u8TofA82E4AYFvlABqZJqvknaOEsf7sO445tZ5OySuuGCdaXg'
        resources: {}