apiVersion: apps/v1
kind: Deployment
metadata:
  name: smd-beta-depl
spec:
  selector:
    matchLabels:
      app: smd-beta
  template:
    metadata:
      labels:
        app: smd-beta
    spec:
      containers:
      - name: smd-beta
        image: eloyk/smd-beta:v1.0.2
        imagePullPolicy: Always
        env:
        - name: DB_NAME
          value: DB_SMD
        - name: SERVER_HOST
          value: mongo-svc
        - name: SERVER_PORT
          value: '27017'        

        - name: FEE_PERCENT
          value: '0'
        - name: DOLLAR_COIN
          value: USDT
        - name: MIN_BUY
          value: '10'
        - name: INIT_BALANCE
          value: '200'
        
        #BOTs
        - name: BOTS_DB
          value: DB_BOTS
        # DAILY TRADE BOT
        - name: DT_CRYPTO
          value: DOT
        - name: DT_DOLLAR
          value: USDT
        - name: DT_PERCENT
          value: '6'
        - name: DT_AMOUNT
          value: '15'
        resources: {}
