apiVersion: apps/v1
kind: Deployment
metadata:
  name: smd-shiba-depl
spec:
  selector:
    matchLabels:
      app: smd-shiba
  template:
    metadata:
      labels:
        app: smd-shiba
    spec:
      containers:
      - name: smd-shiba
        image: eloyk/smd-beta:v1.0.1
        imagePullPolicy: Always
        env:
        - name: DB_NAME
          value: DB_SMD
        - name: SERVER_HOST
          value: mongo-svc
        - name: SERVER_PORT
          value: '27017'        

        - name: FEE_PERCENT
          value: '0'
        - name: DOLLAR_COIN
          value: USDT
        - name: MIN_BUY
          value: '10'
        - name: INIT_BALANCE
          value: '200'
        
        #BOTs
        - name: BOTS_DB
          value: DB_BOTS-shiba
        # DAILY TRADE BOT
        - name: DT_CRYPTO
          value: SHIB
        - name: DT_DOLLAR
          value: USDT
        - name: DT_PERCENT
          value: '6'
        - name: DT_AMOUNT
          value: '15'
        resources: {}