apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - secretName: tls-secret-api
    hosts:
    - api.sgerd.com
    - wordpress.sgerd.com
  rules:
  - host: api.sgerd.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: sgan-backend-svc
            port:
              number: 8080
  - host: wordpress.sgerd.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wordpress-svc
            port:
              number: 8080
